spring.application.name=travel-planner
server.port=8081
planner.travel.cost-per-km=5

planner.food.high=800
planner.food.medium=600
planner.food.low=400

planner.stay.high=3000
planner.stay.medium=2000
planner.stay.low=1200

spring.data.redis.host=localhost
spring.data.redis.port=6379