spring.application.name=travel-planner
server.port=${PORT:8080}
server.address=0.0.0.0
planner.travel.cost-per-km=5

planner.food.low=200
planner.food.medium=400
planner.food.high=700

planner.stay.low=1500
planner.stay.medium=2500
planner.stay.high=4500

spring.data.redis.host=localhost
spring.data.redis.port=6379

planner.distance.api.key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjZlMTY5Mzg1MDJjNzQ1YzhhMzM4NmRmZDFjNjdkOTI0IiwiaCI6Im11cm11cjY0In0=